---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: testing1
  pull: always
  image: golang:1.12-alpine
  commands:
  - echo "test1"
  - echo "test2"

image_pull_secrets:
- dockerconfigjson
